import type { InstallationJob } from "@/lib/types";

/**
 * Fallback data shown only when the live source cannot be reached.
 *
 * Every record here is fictional. Names are deliberately obvious so that a
 * scheduler can tell at a glance that the dashboard is disconnected and is not
 * showing real customers. Never paste production customer data into this file.
 */
export const demoJobs: InstallationJob[] = [
  {
    id: "demo-1",
    invoiceNumber: "INV-DEMO-0001",
    customerName: "DEMO CUSTOMER ONE",
    customerPhone: "011-1111 1111",
    address:
      "NO. 1 JALAN CONTOH 1/1, TAMAN CONTOH MAJU, 81300 JOHOR BAHRU, JOHOR",
    city: "Johor Bahru",
    state: "Johor",
    agentName: "Demo agent",
    totalAmount: 26000,
    paymentPercent: 65,
    paymentBalance: 9100,
    panelQuantity: 18,
    panelRating: 650,
    inverter: "SAJ Hybrid Inverter",
    battery: "Pending confirmation",
    phase: "Three phase",
    inverterType: "Hybrid Inverter",
    derivedInverterModel: "1 X H2-10K-T2",
    sedaStatus: "Pending",
    sldUrl: null,
    packageName: "[3P] HYBRID SAJ JINKO 18 PCS 650W",
    packageType: "Residential",
    installationDate: null,
    customerAvailabilityStatus: "pending_complete",
    preferredInstallationDate: null,
    secondPreferredInstallationDate: null,
    preferredInstallationTime: null,
    availabilityRemarks: "",
    installationApprovalStatus: "pending_seda_approval",
    scheduleStatus: "pending_approval",
    deliveryStatus: "pending_stock",
    deliveryDate: null,
    arrivalDate: null,
    arrivalTime: null,
    stockDetails: "",
    deliveryContactNumber: "011-1111 1111",
    warehouseLocation: "",
    panelDetails: "18 panels × 650W",
    wiringDetails: "",
    batteryDetails: "Pending confirmation",
    inverterBattery: "1 X R6-10K-T2",
    powerOutput: "24 Jinko 620W",
    paymentOverrideStatus: "none",
    paymentOverrideReason: "",
    teams: [],
    remarks: "Demo data — live source unavailable",
    installationRemarks: "",
  },
  {
    id: "demo-2",
    invoiceNumber: "INV-DEMO-0002",
    customerName: "DEMO CUSTOMER TWO",
    customerPhone: "011-2222 2222",
    address: "NO. 2 JALAN CONTOH 2/2, BANDAR CONTOH, 81000 KULAI, JOHOR",
    city: "Kulai",
    state: "Johor",
    agentName: "Demo agent",
    totalAmount: 38000,
    paymentPercent: 100,
    paymentBalance: 0,
    panelQuantity: 24,
    panelRating: 620,
    inverter: "SAJ String Inverter",
    battery: "Not included",
    phase: "Three phase",
    inverterType: "String Inverter",
    derivedInverterModel: "1 X R6-12K-T2",
    sedaStatus: "Pending",
    sldUrl: null,
    packageName: "STRING SAJ JINKO (620W) 24 PCS",
    packageType: "Residential",
    installationDate: null,
    customerAvailabilityStatus: "pending_complete",
    preferredInstallationDate: null,
    secondPreferredInstallationDate: null,
    preferredInstallationTime: null,
    availabilityRemarks: "",
    installationApprovalStatus: "pending_seda_approval",
    scheduleStatus: "ready_to_schedule",
    deliveryStatus: "not_planned",
    deliveryDate: null,
    arrivalDate: null,
    arrivalTime: null,
    stockDetails: "",
    deliveryContactNumber: "011-2222 2222",
    warehouseLocation: "",
    panelDetails: "24 panels × 620W",
    wiringDetails: "",
    batteryDetails: "Not included",
    inverterBattery: "1 X H2-10K-LT2 Hybrid Inverter",
    powerOutput: "16 Jinko 650W",
    paymentOverrideStatus: "none",
    paymentOverrideReason: "",
    teams: [],
    remarks: "Demo data — live source unavailable",
    installationRemarks: "",
  },
  {
    id: "demo-3",
    invoiceNumber: "INV-DEMO-0003",
    customerName: "DEMO CUSTOMER THREE",
    customerPhone: "011-3333 3333",
    address:
      "NO. 3 JALAN CONTOH 3/3, TAMAN CONTOH SETIA, 86000 KLUANG, JOHOR",
    city: "Kluang",
    state: "Johor",
    agentName: "Demo agent",
    totalAmount: 19000,
    paymentPercent: 100,
    paymentBalance: 0,
    panelQuantity: 12,
    panelRating: 620,
    inverter: "SAJ String Inverter",
    battery: "Not included",
    phase: "Single phase",
    inverterType: "String Inverter",
    derivedInverterModel: "1 X R6-5K-T2",
    sedaStatus: "Submitted",
    sldUrl: null,
    packageName: "Solar package",
    packageType: "Residential",
    installationDate: "2026-08-06",
    customerAvailabilityStatus: "propose",
    preferredInstallationDate: "2026-08-06",
    secondPreferredInstallationDate: null,
    preferredInstallationTime: null,
    availabilityRemarks: "Demo record — date confirmed.",
    installationApprovalStatus: "pending_seda_approval",
    scheduleStatus: "pending_approval",
    deliveryStatus: "delivery_scheduled",
    deliveryDate: "2026-08-05",
    arrivalDate: null,
    arrivalTime: null,
    stockDetails: "Panels, inverter, rails and wiring",
    deliveryContactNumber: "011-3333 3333",
    warehouseLocation: "Johor warehouse",
    panelDetails: "12 panels × 620W",
    wiringDetails: "Standard AC/DC wiring",
    batteryDetails: "Not included",
    inverterBattery: "1 X R5-5K-S2",
    powerOutput: "12 Jinko 650W",
    paymentOverrideStatus: "none",
    paymentOverrideReason: "",
    teams: [
      {
        id: "team-1",
        role: "roof",
        teamName: "Roof Team A",
        activity: "pv_panels",
      },
      {
        id: "team-2",
        role: "wiring",
        teamName: "Wiring Team 2",
        activity: "cable_trunking",
      },
    ],
    remarks: "Demo data — live source unavailable",
    installationRemarks: "",
  },
];
