import type { InstallationJob } from "@/lib/types";

export const demoJobs: InstallationJob[] = [
  {
    id: "demo-1",
    invoiceNumber: "INV-1010040",
    customerName: "NGU CHOON JIE",
    customerPhone: "0167492806",
    address:
      "NO.3 JALAN MUTIARA 2/3, TAMAN MUTIARA MAJU, 81300 JOHOR BAHRU, JOHOR",
    city: "Johor Bahru",
    state: "Johor",
    agentName: "Source agent",
    totalAmount: 26288,
    paymentPercent: 65,
    paymentBalance: 36990,
    panelQuantity: 18,
    panelRating: 650,
    inverter: "SAJ Hybrid Inverter",
    battery: "Pending confirmation",
    phase: "Three phase",
    sedaStatus: "Pending",
    sldUrl:
      "https://pub-31ab1252a5544ca19749b476315d9b01.r2.dev/pv_drawings/pv_drawings_28864d9e-b101-4dd0-93c6-5f1333539d33_1780334718135_00c0a2a6.png",
    packageName: "[3P] HYBRID SAJ JINKO 18 PCS 650W",
    installationDate: null,
    customerAvailabilityStatus: "pending",
    preferredInstallationDate: null,
    availabilityRemarks: "",
    installationApprovalStatus: "pending_seda_approval",
    scheduleStatus: "pending_approval",
    deliveryStatus: "pending_stock",
    deliveryDate: null,
    arrivalDate: null,
    stockDetails: "",
    deliveryContactNumber: "0167492806",
    warehouseLocation: "",
    panelDetails: "18 panels × 650W",
    wiringDetails: "",
    batteryDetails: "Pending confirmation",
    paymentOverrideStatus: "none",
    paymentOverrideReason: "",
    teams: [],
    remarks: "Pending SEDA Approval",
  },
  {
    id: "demo-2",
    invoiceNumber: "1005624",
    customerName: "CHUA YONG SOON",
    customerPhone: "0127906966",
    address: "NO 476, JLN KEMPAS 1, BANDAR PUTRA, 81000 KULAI, JOHOR",
    city: "Kulai",
    state: "Johor",
    agentName: "Sunny Tan",
    totalAmount: 38421.5,
    paymentPercent: 100,
    paymentBalance: 0,
    panelQuantity: 24,
    panelRating: 620,
    inverter: "SAJ String Inverter",
    battery: "Not included",
    phase: "Three phase",
    sedaStatus: "Pending",
    sldUrl: null,
    packageName: "STRING SAJ JINKO (620W) 24 PCS",
    installationDate: null,
    customerAvailabilityStatus: "pending",
    preferredInstallationDate: null,
    availabilityRemarks: "",
    installationApprovalStatus: "pending_seda_approval",
    scheduleStatus: "ready_to_schedule",
    deliveryStatus: "not_planned",
    deliveryDate: null,
    arrivalDate: null,
    stockDetails: "",
    deliveryContactNumber: "0127906966",
    warehouseLocation: "",
    panelDetails: "24 panels × 620W",
    wiringDetails: "",
    batteryDetails: "Not included",
    paymentOverrideStatus: "none",
    paymentOverrideReason: "",
    teams: [],
    remarks: "Pending SEDA Approval",
  },
  {
    id: "demo-3",
    invoiceNumber: "INV-1009268",
    customerName: "CHONG SIAT KEE",
    customerPhone: "0108233118",
    address:
      "33 JALAN SETIA MUTIARA 1/2, TAMAN SETIA MUTIARA, 86000 KLUANG, JOHOR",
    city: "Kluang",
    state: "Johor",
    agentName: "Source agent",
    totalAmount: 19000,
    paymentPercent: 100,
    paymentBalance: 19000,
    panelQuantity: 12,
    panelRating: 620,
    inverter: "SAJ String Inverter",
    battery: "Not included",
    phase: "Single phase",
    sedaStatus: "Submitted",
    sldUrl:
      "https://pub-31ab1252a5544ca19749b476315d9b01.r2.dev/pv_drawings/pv_6cc45740-22d8-4450-b7b8-50e0ddf75c04_1776653170815_b3d9f6ae.jpeg",
    packageName: "Solar package",
    installationDate: "2026-08-06",
    customerAvailabilityStatus: "available",
    preferredInstallationDate: "2026-08-06",
    availabilityRemarks: "Customer date confirmed.",
    installationApprovalStatus: "pending_seda_approval",
    scheduleStatus: "pending_approval",
    deliveryStatus: "delivery_scheduled",
    deliveryDate: "2026-08-05",
    arrivalDate: null,
    stockDetails: "Panels, inverter, rails and wiring",
    deliveryContactNumber: "0108233118",
    warehouseLocation: "Johor warehouse",
    panelDetails: "12 panels × 620W",
    wiringDetails: "Standard AC/DC wiring",
    batteryDetails: "Not included",
    paymentOverrideStatus: "none",
    paymentOverrideReason: "",
    teams: [
      {
        id: "team-1",
        role: "roof",
        teamName: "Roof Team A",
        activity: "pv_panels",
      },
      {
        id: "team-2",
        role: "wiring",
        teamName: "Wiring Team 2",
        activity: "cable_trunking",
      },
    ],
    remarks: "Customer date confirmed.",
  },
];
